services:
  frontend:
    image: ${DOCKER_HUB_USER}/${DOCKER_HUB_REPO}:${DOCKER_HUB_FRONTEND_TAG}
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    image: ${DOCKER_HUB_USER}/${DOCKER_HUB_REPO}:${DOCKER_HUB_BACKEND_TAG}
    ports:
      - "8080:8080"
    restart: unless-stopped
